version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/pass.sh
      timeout: 180
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/pass.sh
      timeout: 180
